server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      database: test
      port: 27017
      
  eureka:
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info, ratelimiters, metrics
  health: 
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      showh-details: always

resilience4j:
  circuitbreaker:
    instances:
      subscription:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize:  5
        failureRateThreshold: 50
        waitDurationInOpenState : 15000
        permittedNumberOfCallsInHalfOpenState : 3
        automaticTransitionFromOpenToHalfOpenEnabled : true
  retry: 
    instances: 
      subscription: 
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
                - feign.FeignException$InternalServerError

