server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: series-service
  mongodb:
    embeded:
      version: 4.3.2
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      database: test
      port: 27017
      
  eureka:
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
